config/routes.rb
Rails.application.routes.draw do
  resources :students
  devise_for :users
  resources :abouts do
    root "abouts#new"
  end
  get "dashboard/index"
  root "customers#info"
  post "questioniare" => "api#save"
  get "customer_info" => "customers#info"
  get "customer_detail" => "customers#customer_detail"
  get "delete_customer/:id" => "customers#delete", as: "delete_customer"
  get "sign_up_user" => "customers#signup"
  post "sign_up_user" => "customers#sign_up_user"
  # get "download/:id" => "customers#download", as: "download"
  get "view/:id" => "customers#download", as: "view"
  get "about_api" => "api#get_about_api"

  get "mail_test" =>"customers#mail_test"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  protect_from_forgery :only => [:save]
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!, except: [:save]

  def save
    if create_customerinfo_questioniare(params)
        files = generate_file_list(params[:report])
        images = generate_image_list(params[:image])
        thread = Thread.new do
          UserMailer.sample_email().deliver
          UserMailer.author_email(files, images).deliver
          thread.kill
      end
      render json: { status: 200, message: "Successfully Submitted" }
    else
      render json: { status: 500, message: "Submitted Failed" }
    end
  end
  
  def mail_test
    @user_issues = Questioniare.order("updated_at DESC").first
  end

  def generate_image_list(images)
    new_images = []
    images.each do |image|
      images_hash = Hash.new
      images_hash["image_name"] = image.original_filename
      images_hash["image_data"] = File.read(image)
      new_images.push(images_hash)
    end
    new_images
  end

  def generate_file_list(files)
    files ||= []
    new_files = []
    files.each do |file|
      files_hash = Hash.new
      files_hash["file_name"] = file.original_filename
      files_hash["data"] = File.read(file)
      new_files.push(files_hash)
    end
    new_files
  end

  def delete
    byebug
    customer = CustomerInfo.find(params[:id])
    customer.destroy
    redirect_to customer_info_path
  end

  def info
    @customer = CustomerInfo.all
  end

  def signup
  end

  def sign_up_user
    unless User.where(email: params[:email]).exists?
        user = User.new
        user.email = params[:email]
        user.password = params[:pass]
        if params[:admin] || params[:editor] == "on"
          user.admin = params[:admin]
          user.editor = params[:editor]
        end
        user.save!
        redirect_to customer_info_path
      end
    end

  def create_customerinfo_questioniare(params)
    ActiveRecord::Base.transaction do
      customers = CustomerInfo.where(email: params[:email]).first_or_initialize()
      customers.date_of_birth = params[:DOB]
      customers.name = params[:name]
      customers.contact = params[:contact]
      customers.save!
      question = Questioniare.where(customer_id: customers.id).first_or_initialize()
      question.customer_id = customers.id
      question.eye = params[:eye]
      question.symptom = params[:symptoms]
      question.duration = params[:time]
      question.description = params[:nonListed]
      question.conference = params[:videoConsultation]
      question.save!

      return true
    rescue Exception => ex
      return ex
    end
  end

  def customer_detail
    question = ActiveRecord::Base.connection.execute("select name,email,customer_id,eye,duration,symptom,description from customer_infos ci left join questioniares q on q.customer_id = ci.id where ci.id=" + params["customer_detail"])[0]
    render json: question
  end

  def download
    @customer = CustomerInfo.find(params[:id])
    @question = Questioniare.where(customer_id: params[:id]).first
    pdf = WickedPdf.new.pdf_from_string(render_to_string("download.html.erb", layout: false))
    send_data(pdf,
              filename: "download.pdf",
              type: "application/pdf",
              disposition: "attachment")
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/download.html.erb
<%= wicked_pdf_stylesheet_link_tag %>
<div class="some-div">
  <div class="some-other-div">
    <p>Name: <%= @customer.name %><br><br>
      Contact: <%= @customer.contact %><br><br>
      Email: <%= @customer.email %><br><br>
      Date Of Birth: <%= @customer.date_of_birth %><br><br>

        Problem in <%= @question.eye %> eye <br><br>
         Symptoms: <%= @question.symptom %><br><br> 
         Time Duration: <%= @question.duration %> <br><br> 
        Description:<%= @question.description %> <br><br>
    </p>
  </div>
</div>

app/views/customers/info.html.erb
<%= render "parts/cardTop" %>
<div class="table-btn">
  <div class="data-name">
    <p>Customer List</p>
  </div>
  <table class="table table-bordered table-striped table-hover datatable">
    <thead class="thead-light">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Contact</th>
        <th>Entry_date</th>
        <th>Detail</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @customer.each do |customer| %>
      <tr>
        <td><%= link_to customer.name, view_path(customer)  %></td>
        <td><%= customer.email %></td>
        <td><%= customer.contact %></td>
        <td><%= customer.updated_at %></td>
        <td><%= link_to "PDF  <i class='bx bx-download'></i>".html_safe, view_path(customer)%></td>
        <td class="action"><button type="button" class="icon-btn" data-toggle="modal" data-target="#myModal"
            id=<%= customer.id %> onclick="onViewClick(this.id)"><i class='bx bx-show eye'></i></button>
          <%= link_to '<i class="bx bx-trash t-btn"></i>'.html_safe, delete_customer_path(customer), method: :delete, data: { confirm: "Are you sure?" }, class: "icon-btn" %>
        </td>
      </tr>

      <% end %>
    </tbody>
  </table>


  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="model-popup BodyWrapper_body__vPZ4s">
      <div class="modal-content">
        <div class="modal-btn">
          <div class="modal-header">

            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Report of: <p class="pop-name" id="customer_name"></p>
            </h4>
            <div class="email-btn">
              <i class='bx bx-envelope mail'></i>
              <p class="pop-email" id="customer_info"></p>
            </div>
          </div>
          <div class="modal-body">
            <table id="test">
              <div class="popup">
                <div class="row">
                  <div class="col-md-6">
                    <div class="desc">
                      Eye:
                    </div>
                    <p class="text-area" id="eye"></p>
                  </div>
                  <div class="col-md-6">
                    <div class="desc">
                      Duration:
                    </div>
                    <p class="text-area" id="duration"></p>
                  </div>
                  <div class="col-md-6">
                    <div class="desc">
                      Symptoms:
                    </div>
                    <p class="text-area" id="symptom"></p>
                  </div>
                  <div class="col-md-12">
                    <div class="desc">
                      Description:
                    </div>
                    <p class="text-area area-desc" id="description"></p>
                  </div>
                </div>
              </div>
          </div>
          </table>
        </div>
        <%# <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div> %>
      </div>
      </div>
    </div>
  </div>
</div>
<%= render 'parts/cardBottom' %>

<script>
  $(document).ready(function () {
    $('.datatable').DataTable();

  });

  function popup() {
    $(document).ready(function () {
      $('#myModal').modal();
    });
  }

  function onViewClick(id) {
    $.ajax({
      type: "get",
      url: "customer_detail",
      //dataType: "json",
      data: {
        "customer_detail": id
      },
      success: function (data) {
        $("#customer_info").html(data["email"]);
        $("#customer_name").html(data["name"]);
        $("#description").html(data["description"]);
        $("#eye").html(data["eye"]);
        $("#duration").html(data["duration"]);
        $("#symptom").html(data["symptom"]);
        // testdata = 'description: ' + data["description"] + 'eye: ' + data["eye"] + 'duration: ' + data[
        // "duration"] + 'symptom: ' + data["symptom"]
        $("#test").text(testdata)
      },
      error: function (errorMessage) {},
    })
  };
</script>

app/views/customers/mail_test.html.erb
<!DOCTYPE html>
<html>

<head>
    <style>
        .full {
            padding-bottom: 10px;
            color: #949191;
        }

        .form {
            padding: 20px;
            width: 435px;
            background-color: white;
            border: 1px solid white;
            box-shadow: 0px 0px 13px 0px #bdbbbb8f;
            border-radius: 10px;
            margin: auto;
            margin-bottom: 10px;
        }

        .bold {
            font-weight: 700;
            display: flex;
        }

        .full p {
            margin-bottom: 0px !important;
        }

        .small {
            font-weight: 500;
            font-size: 1rem;
            text-transform: capitalize;
            color: #000000d9;
        }

        .email .small {
            text-transform: unset;
        }

        h3 {
            color: #040404b0;
            text-align: center;
        }

        .description .full {
            padding-bottom: 0;
        }

        .first {
            min-width: 155px;
        }
    </style>
</head>

<body>
    <div class="form">
        <h3>Author Email</h3>
        <hr>
        <div class="text-field">
            <div class="full">
                <div class="bold">
                    <p class="first">Full Name:</p>
                    <p class="small">Test</p>
                </div>
            </div>
            <div class="full">
                <div class="email">
                    <div class="bold">
                        <p class="first"> Email:</p>
                        <p class="small"> susan@gmail.com</p>
                    </div>
                </div>
            </div>
            <div class="full">

                <div class="bold">
                    <p class="first"> Date of Birth: </p>
                    <p class="small">12/12/1998</p>
                </div>
            </div>
            <div class="full">

                <div class="bold">
                    <p class="first">Phone: </p>
                    <p class="small">123123</p>
                </div>
            </div>
            <div class="full">
                <div class="bold">
                    <p class="first"> Eye:</p>
                    <p class="small"> asdf</p>
                </div>

            </div>
            <div class="full">

                <div class="bold">
                    <p class="first">Duration: </p>
                    <p class="small">asdf</p>
                </div>
            </div>
            <div class="full">
                <div class="bold">
                    <p class="first">Symptoms:</p>
                    <p class="small">Pain Itchy Red Eye Watery eye Loss/Reduced Vision No symptoms</p>
                </div>

            </div>
            <div class="full">
                <div class="bold">
                    <p class="first">Video Consultant:</p>
                    <%if @user_issues.conference == true %>
                    <p class="small">I want a video consultant</p>
                    <%else%>
                    <p class="small">I don't want a video consultant</p>
                    <%end%>
                </div>
            </div>
        </div>
        <hr>
        <div class="description">
            <div class="full">
                <div class="bold">
                    <p class="first"> Description:</p>
                </div>
                <p class="small"> asdfasdfasda aaaaaaaaaaa aaaaaaaaaa aaaaaaaaaa yyyyyyyyyy yyyyyyy yyyyyyyyyy</p>
            </div>
        </div>
    </div>

</body>

</html>

app/views/customers/signup.html.erb
<div class="form-input">
    <div class="sign-form ">
        <form method="post">
            <div>
                <h2>Sign Up</h2>
                <div class="label-btn">
                    <label class="email">Email: </label> <input type="email" name="email" class="flex-btn">
                </div>
                <div class="label-btn">
                    <label class="email">Password: </label><input type="password" name="pass" class="flex-btn">
                </div>
                <div class="label-btn">
                    <div class="radio-item">
                        <input type="radio" name="editor" id="rd-item">
                        <label class="check-box" for="rd-item">Admin</label>
                    </div>
                    <div class="radio-item">
                        <input type="radio" name="editor" id="rd-item1">
                        <label for="rd-item1">Editor</label>
                    </div>
                </div>
                <div class="submit-item">
                    <div class="btn btn btn-primary btn-lg">
                        <%= button_to "Submit", {class:'submit-btn'} %>
                    </div>
                </div>
        </form>
    </div>
</div>