config/routes.rb
Rails.application.routes.draw do
  resources :students
  devise_for :users
  resources :abouts do
    root "abouts#new"
  end
  get "dashboard/index"
  root "customers#info"
  post "questioniare" => "api#save"
  get "customer_info" => "customers#info"
  get "customer_detail" => "customers#customer_detail"
  get "delete_customer/:id" => "customers#delete", as: "delete_customer"
  get "sign_up_user" => "customers#signup"
  post "sign_up_user" => "customers#sign_up_user"
  # get "download/:id" => "customers#download", as: "download"
  get "view/:id" => "customers#download", as: "view"
  get "about_api" => "api#get_about_api"

  get "mail_test" =>"customers#mail_test"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: %i[ show edit update destroy ]
  # before_action :authenticate_user!

  # GET /abouts or /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1 or /abouts/1.json
  def show
  end

  # GET /abouts/new
  def new
    @bctitle = "About Us"
    @bc1 = "About Us"
    @back = "/"
    if About.count == 0
      @about = About.new
    else
      @about = About.first
    end
  end

  # GET /abouts/1/edit
  def edit
    @bctitle = "About Us"
    @bc1 = "About Us"
    @back = "/"
  end



  # POST /abouts or /abouts.json
  def create
    @about = About.new(about_params)
    
    respond_to do |format|
      if @about.save
        format.html { redirect_to @about, notice: "About was successfully created." }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1 or /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to abouts_path, notice: "About was successfully updated." }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1 or /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to abouts_url, notice: "About was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_about
    
    @about = About.find(params[:id])
    
  end

  # Only allow a list of trusted parameters through.
  def about_params
    params.require(:about).permit(:privacy, :welcome, :thank_you, :terms_and_condition)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/abouts/_form.html.erb
<%= simple_form_for(@about) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="form-group">
      <%= f.input :privacy, input_html: { class: "summernote" } %>
    </div>
    <div class="form-group">
      <%= f.input :welcome, as: :text, input_html: { class: "summernote" } %>
    </div>
    <div class="form-group">
      <%= f.input :thank_you, input_html: { class: "summernote" } %>
    </div>
    <div class="form-group">
      <%= f.input :terms_and_condition, input_html: { class: "summernote" } %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<%= render 'parts/breadcrumb' %>
<%= render 'parts/cardTop' %>

<%= render 'form', about: @about %>


<%= render 'parts/cardBottom' %>

app/views/abouts/index.html.erb
<%= render "parts/breadcrumb" %>
<%= render "parts/cardTop" %>


<h1>Abouts</h1>

<table class="table table-bordered table-striped table-hover datatable no-wrap v-middle mb-0 ">
  <thead>
    <tr>
      <th>Privacy</th>
      <th>Welcome</th>
      <th>Thank you</th>
      <th>Terms and condition</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @abouts.each do |about| %>
      <tr>
        <td><%= about.privacy %></td>
        <td><%= about.welcome %></td>
        <td><%= about.thank_you %></td>
        <td><%= about.terms_and_condition %></td>
        <td>
          <%= link_to "Show", about %>
          <%= link_to "Edit", edit_about_path(about) %>
          <%= link_to "Destroy", about, method: :delete, data: { confirm: "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render "parts/cardBottom" %>

app/views/abouts/new.html.erb
<%= render "parts/breadcrumb" %>
<%= render "parts/cardTop" %>
<%= render "form", about: @about %>


<%= render "parts/cardBottom" %>

app/views/abouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Privacy:</strong>
  <%= @about.privacy %>
</p>

<p>
  <strong>Welcome:</strong>
  <%= @about.welcome %>
</p>

<p>
  <strong>Thank you:</strong>
  <%= @about.thank_you %>
</p>

<p>
  <strong>Terms and condition:</strong>
  <%= @about.terms_and_condition %>
</p>

<%= link_to 'Edit', edit_about_path(@about) %> |
<%= link_to 'Back', abouts_path %>