config/routes.rb
Rails.application.routes.draw do
  resources :students
  devise_for :users
  resources :abouts do
    root "abouts#new"
  end
  get "dashboard/index"
  root "customers#info"
  post "questioniare" => "api#save"
  get "customer_info" => "customers#info"
  get "customer_detail" => "customers#customer_detail"
  get "delete_customer/:id" => "customers#delete", as: "delete_customer"
  get "sign_up_user" => "customers#signup"
  post "sign_up_user" => "customers#sign_up_user"
  # get "download/:id" => "customers#download", as: "download"
  get "view/:id" => "customers#download", as: "view"
  get "about_api" => "api#get_about_api"

  get "mail_test" =>"customers#mail_test"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer text-center text-muted">
                All Rights Reserved by Adminmart. Designed and Developed by <a
                    href="https://wrappixel.com">WrapPixel</a>.
            </footer>

app/views/layouts/_leftNav.html.erb
<aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item"> <a class="sidebar-link sidebar-link" href="<%= customer_info_path %>"
                        aria-expanded="false"><i data-feather="user" class="feather-icon"></i><span
                            class="hide-menu">Customer Info</span></a></li>
                <li class="sidebar-item"> <a class="sidebar-link sidebar-link" href="<%= abouts_path%>"
                        aria-expanded="false"><i data-feather="home" class="feather-icon"></i><span
                            class="hide-menu">About Us</span></a></li>
                <%  if current_user.admin? %>
                <li class="sidebar-item"> <a class="sidebar-link sidebar-link" href="<%= sign_up_user_path %>"
                        aria-expanded="false"><i data-feather="log-in" class="feather-icon"></i><span
                            class="hide-menu">Sign Up</span></a></li>
                <%end%>
                <li class="list-divider"></li>


            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>

app/views/layouts/_preloader.html.erb
<div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Virtual Eye Consultant | Admin </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
  <%# <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"> %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%# <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote-bs4.min.css" integrity="sha512-pDpLmYKym2pnF0DNYDKxRnOk1wkM9fISpSOjt8kWFKQeDmBTjSnBZhTd41tXwh8+bRMoSaFsRnznZUiH9i3pxA==" crossorigin="anonymous" /> %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote-lite.min.css"
    integrity="sha512-wXEyXmtKft9mEiu8LTc3+3BQ95aYbvxgvzH4IzFHOwvGlA14B6zREXD4CRmUPx8r2Z1RVUOXS47bwjsotSlZkQ=="
    crossorigin="anonymous" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote.min.css"
    integrity="sha512-KbfxGgOkkFXdpDCVkrlTYYNXbF2TwlCecJjq1gK5B+BYwVk7DGbpYi4d4+Vulz9h+1wgzJMWqnyHQ+RDAlp8Dw=="
    crossorigin="anonymous" />
  <%# <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/plugin/databasic/summernote-ext-databasic.min.css" integrity="sha512-yJAN+L5Id+AZIk7Br3DdMqzNhADLCrKQiHLrCJVaJvGFurSzx76FOH8Rbrm2+p8htvltFSBHIvjxE4ons7whOw==" crossorigin="anonymous" /> %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


  <script src="https://unpkg.com/boxicons@latest/dist/boxicons.js"></script>
  <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote.min.js"
    integrity="sha512-kZv5Zq4Cj/9aTpjyYFrt7CmyTUlvBday8NGjD9MxJyOY/f2UfRYluKsFzek26XWQaiAp7SZ0ekE7ooL9IYMM2A=="
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.7.0/css/buttons.dataTables.min.css">
  <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/buttons/1.7.0/js/dataTables.buttons.min.js"></script>
</head>
<% if user_signed_in? %>

<body>
  <%#= render 'layouts/preloader' %>

  <div id="main-wrapper" data-theme="light" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full"
    data-sidebar-position="fixed" data-header-position="fixed" data-boxed-layout="full">
    <%= render 'layouts/topNav' %>
    <%= render 'layouts/leftNav' %>
    <div class="page-wrapper">
      <%= yield %>
      <%= toastr_flash %>
      <%#= render 'layouts/footer' %>
    </div>
  </div>
  </div>
</body>
<%else%>

<body>
  <div class="div1">
    <div class="border">
      <div class="margin">
        <div class="main_body">
          <%= yield %>
        </div>
        <div class="footer">
          <p>Design and Developed by: <span><a href="http://www.axiossoftware.com/">Axios Software</a></span></p>
        </div>
      </div>
    </div>

  </div>
  </div>
  </div>
</body>
<style>
  .div1 {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    width: 100%;
    flex-direction: column;
    background-image: url('/Group 58.png');
  }

  .border {
    box-shadow: 2px 2px 4px #8888;
    background-color: White;
    border-radius: 10px;

  }

  .margin {
    margin: 20px;
  }

  .margin {
    margin: 20px;
  }

  .border {
    min-width: 30%;

  }
</style>
<%end%>

</html>